'No': 0
TTA: 3
batch_size: 12
config: config/config512-0.yaml
epoch: 40
es_patience: 5
factor: 0.3
fig_size: 512
hair: 4
in_features: 1280
lr: 0.001
microscope: 0.25
n_split: 5
num_workers: 4
pass_list:
- 10
patience: 2
pin_memory: false
pretrained: efficientnet-b1
resume: null
seed: 41
verbose: 1
