# global related
seed: 42
# pyrotch related
num_workers: 4
pin_memory: False
# training related
n_split: 5
batch_size: 32
epoch: 30
lr: 0.001
es_patience: 5
patience: 2
factor: 0.3
TTA: 3
# model related
in_features: 1280
pretrained: efficientnet-b1
# dataset related
microscope: 0.25
hair: 4
