# global related
seed: 42
# pyrotch related
num_workers: 4
pin_memory: False
in_features: 1408
pretrained: efficientnet-b2
# training related
n_split: 5
batch_size: 64
epoch: 20
lr: 0.001
es_patience: 5
patience: 2
factor: 0.3
TTA: 3
# dataset related
microscope: 0.5
hair: 4
