# global related
seed: 42
# pyrotch related
num_workers: 4
pin_memory: False
in_features: 1280
pretrained: efficientnet-b1
# training related
n_split: 5
batch_size: 16
epoch: 20
lr: 0.001
es_patience: 5
patience: 2
factor: 0.3
TTA: 3
# dataset related
microscope: 0.25
hair: 4
