'No': 2
TTA: 3
batch_size: 12
config: config/config768-2.yaml
epoch: 20
es_patience: 5
factor: 0.3
fig_size: 768
hair: 6
in_features: 1280
lr: 0.001
microscope: 0.25
n_split: 5
num_workers: 4
pass_list:
- 1
- 2
- 3
patience: 2
pin_memory: false
pretrained: efficientnet-b0
resume: null
seed: 42
verbose: 1
