'No': 1
TTA: 3
batch_size: 16
config: config/config384-1.yaml
epoch: 30
es_patience: 5
factor: 0.3
fig_size: 384
hair: 4
in_features: 1408
lr: 0.001
microscope: 0.25
n_split: 5
num_workers: 4
patience: 2
pin_memory: true
pretrained: efficientnet-b2
resume: null
seed: 42
verbose: 1
